# LocalStack with S3, SQS, DynamoDB, SNS, Secrets, Lambda, Logs, EventBridge, Step Functions

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,dynamodb,sns,secretsmanager,ssm,lambda,logs,events,stepfunctions
      - DEBUG=0
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  localstack-data:
